<?php

namespace Acme\AdminBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class EventListController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Acme\AdminBundle\Controller\EventListController();
        return $instance;
    }
}
